### ISSUE TITLE
アンバサダー用フロントエンドへ統合商品マスタテーブル、Meitex商品マスタテーブル、独自登録商品マスタテーブル情報を返すAPIを作成

### ISSUE THREAD

**Issue by suzuyu33z** [tech0-Jokers/office_pacrico_backend#30]
統合商品マスタテーブル、Meitex商品マスタテーブル、独自登録商品マスタテーブル情報を返すAPIの作成をお願いします。

エンドポイント："/api/snacks/"
ほしいデータ：以下をリスト形式でほしい
"id"、"name"、 "description"、 "image_url"

【レスポンスの例】
{
  "products": [
    {
      "id": 1,
      "name": "データベース商品1",
      "description": "説明文",
      "image_url": "https://example.com/db_product1.jpg"
    },
    {
      "id": 2,
      "name": "データベース商品2",
      "description": "説明文",
      "image_url": "https://example.com/db_product2.jpg"
    }
  ]
}

【FastAPIコード例】
@app.get("/api/snacks/")
def get_snacks(organization_id: int, db: Session = Depends(get_db)):
    # Meitex商品を取得
    meitex_query = (
        db.query(
            IntegratedProducts.product_id,
            MeitexProductMaster.product_name,
            MeitexProductMaster.product_explanation,
            MeitexProductMaster.product_image_url,
        )
        .join(MeitexProductMaster, IntegratedProducts.meitex_product_id == MeitexProductMaster.meitex_product_id)
    )

    # 独自登録商品を取得
    independent_query = (
        db.query(
            IntegratedProducts.product_id,
            IndependentProductMaster.product_name,
            IndependentProductMaster.product_explanation,
            IndependentProductMaster.product_image_url,
        )
        .join(IndependentProductMaster, IntegratedProducts.independent_product_id == IndependentProductMaster.independent_product_id)
        .filter(IndependentProductMaster.organization_id == organization_id)
    )

    # データベースから取得したデータをリスト形式に変換
    meitex_products = [
        {
            "id": p.product_id,
            "name": p.product_name,
            "description": p.product_explanation,
            "image_url": p.product_image_url,
        }
        for p in meitex_query.all()
    ]

    independent_products = [
        {
            "id": p.product_id,
            "name": p.product_name,
            "description": p.product_explanation,
            "image_url": p.product_image_url,
        }
        for p in independent_query.all()
    ]

    # データベースデータをマージ
    all_products = meitex_products + independent_products

    return {"products": all_products}

**Comment by ryosan-dolphin-joker7** [comment]
@suzuyu33z 
@itashou21 

Pull Requestをマージしました！
Azureでのデプロイも出来ており、動作も確認済みです。

explanationとdescriptionを分けている理由はありますか？
できれば統一した方が分かりやすいと思います。

ところで、
GET/products/{organization_id}　Get Products By Organization
との違いって、商品マスターのテーブルを結合（union）していることでしょうか？

**Comment by itashou21** [comment]
@ryosan-dolphin-joker7 さん
すみません、遅くなりました！

＞explanationとdescriptionを分けている理由はありますか？
＞できれば統一した方が分かりやすいと思います。
特に理由はないと思います！
昨日のMtgだと、バックに合わせる形で修正していくってことですよね？

＞GET/products/{organization_id}　Get Products By Organization
＞との違いって、商品マスターのテーブルを結合（union）していることでしょう＞か？
微妙に返している内容が異なります。
①商品ID、商品名、商品の説明、画像URL
②商品ID、商品名、画像URL、販売金額、在庫量
②がGET/products/{organization_id}に該当します！

フロントで取捨選択できるようであれば、APIは１つでも良いかもです。
