### ISSUE TITLE
アンバサダー用フロントエンドで「お菓子を新規登録」した際に、各テーブルにデータを格納したい

### ISSUE THREAD

**Issue by suzuyu33z** [tech0-Jokers/office_pacrico_backend#33]
アンバサダー用フロントエンドで「お菓子を新規登録」した際に、各テーブルにデータを格納したい。
<img width="518" alt="image" src="https://github.com/user-attachments/assets/fd9c3bb5-3d28-43d5-ad05-45ac41ac1db3">

お菓子の入庫時に、独自でお菓子を登録する際、「独自登録商品マスタ」「統合商品マスタ」にお菓子の情報を登録したい。

統合商品マスタ：独自登録商品id
独自登録商品マスタ：組織id、商品名、商品説明、商品画像URL※
※Next.jsから送るのはバイナリデータなので、FastAPI側でAzure Blob StorageにアップロードおよびURL取得をお願いします。

エンドポイント："/api/newsnacks/?organization_id=${organizationId}"

（送信するデータ例）
organization_id: 1
name: ポテトチップス
description: サクサクでおいしいポテトチップス
image: potato_chips.jpg (バイナリデータ)

**Comment by suzuyu33z** [comment]
現在、登録制工事には添付のデータがバック→フロントへ送られていますが、product_nameも返していただけますか？

<img width="746" alt="image" src="https://github.com/user-attachments/assets/9ba326b5-4ef1-41c5-bc56-63faae4ac82f">

**Comment by itashou21** [comment]
product_nameも返すようにしておきました～！
